# import os
# from dotenv import load_dotenv
# # new openai 1.0+ interface uses a client object
# from openai import OpenAI

# # ensure .env is loaded (override=True not needed here)
# load_dotenv()

# # create a reusable client instance; key assigned lazily later
# client = OpenAI()

# # simple wrapper function for generating text completions
# # the interface matches the old `generate_response(prompt)` signature.

# def generate_response(prompt: str) -> str:
#     """Return text generated by the OpenAI API for a given prompt.

#     The prompt string should contain any system instructions or user
#     context.  Under the hood we call the ChatCompletion endpoint with a
#     single system message.  The model can be configured via the
#     OPENAI_MODEL environment variable (default "gpt-3.5-turbo").
#     """
#     # ensure the API key is available on the client
#     if not client.api_key:
#         key = os.getenv("OPENAI_API_KEY")
#         if not key:
#             raise RuntimeError("OPENAI_API_KEY is not set in the environment")
#         client.api_key = key

#     model = os.getenv("OPENAI_MODEL", "gpt-3.5-turbo")

#     try:
#         resp = client.chat.completions.create(
#             model=model,
#             messages=[{"role": "system", "content": prompt}],
#             max_tokens=600,
#             temperature=0.2,
#         )
#     except Exception as e:
#         raise RuntimeError(f"OpenAI API request failed: {e}")

#     # extract text from first choice (Pydantic object has attributes)
#     # the message object has `.content` and `.role` properties.
#     text = getattr(resp.choices[0].message, "content", "")
#     return text.strip()


import os
from dotenv import load_dotenv
from openai import OpenAI

# Load environment variables
load_dotenv()

# Create reusable OpenAI client
client = OpenAI()


def generate_response(prompt: str) -> str:
    """
    Generate text using OpenAI Responses API.
    Compatible with agent architecture.
    """

    model = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")

    try:
        response = client.responses.create(
            model=model,
            input=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            temperature=0.2,
            max_output_tokens=600,
        )

        return response.output_text.strip()

    except Exception as e:
        raise RuntimeError(f"OpenAI API request failed: {e}")